version: '3'

services:
  app:
    image: ghcr.io/smonn/algo-devkit:v3.15.0-stable
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:indexer_db
    environment:
      PGPORT: 5432
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres

  indexer_db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - indexer_db_data:/var/lib/postgresql/data

volumes:
  indexer_db_data: