version: "3"

services:
  app:
    image: ghcr.io/deptagency/algorand-devcontainer:latest

    init: true

    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock

    entrypoint: sleep infinity
