version: "3"

services:
  app:
    image: ghcr.io/deptagency/algorand-devcontainer:latest
    init: true
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      PGPORT: 5432
      PGHOST: indexer_db
      PGUSER: algorand
      PGDATABASE: indexer_db
      PGPASSWORD: algorand

  algod:
    container_name: algokit_algod
    image: makerxau/algorand-sandbox-dev:latest
    ports:
      - 4001:4001
      - 4002:4002
      - 9392:9392

  indexer:
    container_name: algokit_indexer
    image: makerxau/algorand-indexer-dev:latest
    ports:
      - 8980:8980
    restart: unless-stopped
    environment:
      ALGOD_HOST: algod
      POSTGRES_HOST: indexer_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db
    depends_on:
      - indexer_db
      - algod

  indexer_db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - 6432:5432
    environment:
      POSTGRES_PASSWORD: algorand
      POSTGRES_USER: algorand
      POSTGRES_DB: indexer_db
    volumes:
      - indexer_db_data:/var/lib/postgresql/data

volumes:
  indexer_db_data:
