# Environment variables

# General
export LANG=en_US.UTF-8

# Algorand
export ALGORAND_NODE="$HOME/node"
export ALGORAND_MAINNET="$ALGORAND_NODE/mainnet"
export ALGORAND_PRIVNET="$ALGORAND_NODE/privnet"
export ALGORAND_DATA="$ALGORAND_PRIVNET/data"
export INDEXER_ROOT="$HOME/indexer"
export INDEXER_DATA="$INDEXER_ROOT/data"
export PATH="$ALGORAND_NODE:$INDEXER_ROOT:$PATH"
